### ISSUE TITLE
Method not implemented: Kinvey.Defer.deferred

### ISSUE THREAD

**Issue by Sandeep125** [KinveyApps/Ionic-Starter#1]
I can't able to fix this issue. Errors at console.
![1](https://cloud.githubusercontent.com/assets/14305940/12693756/ba42cc5c-c73a-11e5-88e8-8f0d1a5c5c0b.jpg)

I have followed all the instructions as suggested in readme.

**Comment by thomasconner** [comment]
Hey @Sandeep125. Thanks for reporting the issue. We have identified a bug in the library and are working on a fix. I will let you know when a new release is available.

**Comment by thomasconner** [comment]
@Sandeep125 this has been fixed with the latest release of the Kinvey Angular library (http://devcenter.kinvey.com/angular/timeline). Please pull the latest from master and run `npm install` again.
