### ISSUE TITLE
setup.js doesn't work on Windows 7 machine.

### ISSUE THREAD

**Issue by aatifhshah** [KinveyApps/Ionic-Starter#2]
[npm-debug.txt](https://github.com/KinveyApps/Ionic-Starter/files/160528/npm-debug.txt)

**Comment by thomasconner** [comment]
I have removed setup.js. The app should now work on a Windows 7 machine. I am going to close the issue but if you still have a problem please let me know and I will reopen the issue. Thanks for reporting.
